Backend/cms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path("AapKaBaap/", admin.site.urls),
    path('', include('website.urls')),
    path('user/', include('user_onboarding.urls')),
    path('ratings/', include('ratings.urls')),
    path('api/comment/', include('comment.urls')),
    path('api/pax/', include('pax_deployed.urls')),
    path('api/media/', include('file_upload.urls')),
    path('api/feedback/', include('feedback.urls')),
    path('api/inspection-feedback/', include('inspection_feedback.urls')),
    path('complain/', include('notified_data.urls')),
    path('api/analytics/',include('analytics.urls')),
    path('pdf/', include('pdf.urls')),
    path('station/', include('station.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'cms.views.handler403'

Backend/inspection_feedback/urls.py
from django.urls import path

from .views import inspection_feedback, InspectionFeedbackApi,UpdateFeedbackStatusApi,ListRetrieveUpdateDeleteFeedbackApi, ListFeedbacksByDateApi,get_inspection_feedback_images,delete_inspection_feedback_image_api



urlpatterns = [
    path('enter/', inspection_feedback, name='inspection_feedback'),
    path('add/', InspectionFeedbackApi.as_view(), name='add_inspection_feedback'),
    path('update-feedback-status/<int:pk>/', UpdateFeedbackStatusApi.as_view(), name='update_feedback_status_api'),
    
    path('feedbacks/', ListFeedbacksByDateApi.as_view(), name='list_feedbacks_by_date_api'),
    path('feedback/<int:pk>/', ListRetrieveUpdateDeleteFeedbackApi.as_view(), name='feedback_api'),

    
    path('<int:feedback_id>/images/', get_inspection_feedback_images, name='get_inspection_feedback_images'),
    path('<int:feedback_id>/images/<int:image_id>/', delete_inspection_feedback_image_api, name='delete_inspection_feedback_image'),
]

Backend/pdf/urls.py
from django.urls import path

from .views import (
    which_pdf, 
    daily_buyers_rating_sheet_pdf, 
    daily_pdf, 
    monthly_pdf, 
    get_pre_daily_feedback, 
    signature_daily_evaluation, 
    complaints_pdf,
    bde_monthly_pdf,
    bde_daily_consolidated_pdf,
    mail_monthly_daily_reports
)


urlpatterns = [
    path('whichpdf', which_pdf, name='whichpdf'),
    path('daily/', daily_pdf, name='daily_pdf'),
    path('daily-buyers-sheet/', daily_buyers_rating_sheet_pdf, name='daily_buyers_rating_sheet_pdf'),
    path('daily/bde-consolidated/', bde_daily_consolidated_pdf, name='bde_daily_consolidated_pdf'),
    path('monthly/', monthly_pdf, name='monthly_pdf'),
    path('monthly/mail-daily-reports/', mail_monthly_daily_reports, name='mail_monthly_daily_reports'),
    path('monthly/bde/', bde_monthly_pdf, name='bde_monthly_pdf'),
    path('get_pre_daily_feedback', get_pre_daily_feedback, name='get_pre_daily_feedback'),
    path('signature_daily_evaluation', signature_daily_evaluation, name='signature_daily_evaluation'),
    path('complaints/details/<str:date>/', complaints_pdf, name='complaints_pdf'),
]

Backend/pdf/models.py
from django.db import models

from station.models import Station
from user_onboarding.models import User


class DailyEvaluationVerification(models.Model):
    verified_eval_date = models.DateField(null=True)
    verified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    station=models.ForeignKey(Station, on_delete=models.CASCADE, default=1)
    email = models.EmailField(null=True)
    verified_at = models.DateTimeField(auto_now=True)
    verification_status= models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=200, default='')
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=200, default='')

Backend/task/models.py
from django.db import models
import datetime

from station.models import Station


class Task(models.Model):
    TASK_TYPE_CHOICES = (
        ('D', 'Daily'),
        ('A', 'Alternately'),
        ('W', 'Weekly'),
        ('F', 'Fortnightly'),
        ('B', 'Biannually'),
        ('H', 'Half Yearly'),
        ('Q', 'Quaterly'),
        ('BW', 'Biweekly'),
        ('M', 'Monthly'),
        ('Y', 'Yearly')
    )

    WEEKDAY_CHOICES = [
        ('0', 'Monday'),
        ('1', 'Tuesday'),
        ('2', 'Wednesday'),
        ('3', 'Thursday'),
        ('4', 'Friday'),
        ('5', 'Saturday'),
        ('6', 'Sunday'),
    ]

    task_id = models.IntegerField(null=True, default=1)
    task_description = models.TextField()
    service_type = models.CharField(max_length=200)
    cleaning_cycle_days = models.IntegerField()  # frequesncy per 2 years
    cleaning_cycle_type = models.CharField(
        max_length=100, choices=TASK_TYPE_CHOICES, default='D')
    cleaning_cycle_day_freq = models.IntegerField()
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=200)
    task_type = models.CharField(max_length=5, default='A')
    weekday = models.CharField(
        max_length=100, choices=WEEKDAY_CHOICES, blank=True, null=True, default='0')
    biweekday = models.CharField(
        max_length=100, choices=WEEKDAY_CHOICES, blank=True, null=True, default='5')
    alternate_day_start = models.DateField(
        blank=True, null=True, default=datetime.date(2023, 1, 1))
    biannually_date1 = models.DateField(
        blank=True, null=True, default=datetime.date.today)
    biannually_date2 = models.DateField(
        blank=True, null=True, default=datetime.date.today)

    def __str__(self):
        return self.task_description


class CycleDate(models.Model):
    task = models.ForeignKey(
        Task, on_delete=models.CASCADE, related_name='cycles')
    cycle_type = models.CharField(max_length=200)
    cycle = models.DateField(null=True)
    next_cycle = models.DateField(null=True)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.station.station_name} - {self.task.task_description} - {self.cycle}"

Backend/inspection_feedback/views.py
import logging
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.decorators import permission_classes, api_view
from rest_framework.permissions import IsAuthenticated
from django.core.exceptions import ValidationError
from django_ratelimit.decorators import ratelimit
from django.utils.decorators import method_decorator
from django.core import serializers
from rest_framework.exceptions import PermissionDenied
from rest_framework.decorators import authentication_classes, permission_classes
from rest_framework.generics import RetrieveUpdateDestroyAPIView,ListAPIView
from django.shortcuts import get_object_or_404

from .models import Inspection_feedback,Image
from .serializers import InspectionFeedbackSerializer,ImageSerializer
from .utils import upload_inspection_feedback_images
from website.utils import check_permission
from website.decorators import allowed_users
from website.permissions import IsRailwayAdmin


@api_view(['GET'])
@permission_classes([IsAuthenticated])
@ratelimit(key='ip', rate='50/m', block=True)
@allowed_users(['supervisor', 'contractor', 'railway admin', 'officer', "chi_sm"])
def inspection_feedback(request):
    try:
        user = request.user
        station = user.station
        station_json = serializers.serialize('json', [station])
        role = user.user_type
        sup = role.name

        if check_permission(user):
            context = {
                'sup': sup, 
                'station': station_json
            }
            return Response(context, status=status.HTTP_200_OK)
        else:
            messages = f"{sup} don't have permission to do this task"
            return Response({'message': messages}, status=status.HTTP_403_FORBIDDEN)
        
    except Exception as e:
        message = 'An error occurred while loading the Inspection Feedback page'
        logging.exception(f"{message} in inspection_feedback: {repr(e)}")
        return Response({"message": message}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


@permission_classes([IsAuthenticated])
@method_decorator(ratelimit(key='ip', rate='50/m', block=True), name='dispatch')
class InspectionFeedbackApi(APIView):
    def post(self, request):
        try:
            data = request.data.copy()
            user = request.user
            station = user.station
            role = user.user_type
            sup = role.name

            if check_permission(user) and sup in ["supervisor", "contractor", "railway admin", "officer", "chi_sm"]:
                try:
                    existing_feedback = Inspection_feedback.objects.get(station=station, date=data['date'])
                    if existing_feedback.user == user and existing_feedback.status == 'Pending':
                        data.update({'updated_by': user.username})
                        serializer = InspectionFeedbackSerializer(
                            instance=existing_feedback,
                            data=data,
                            partial=True
                        )
                        response_data = {'message': 'Inspection Feedback is updated'}
                    else:
                        raise PermissionDenied("You don't have permission to update this feedback.")
                    
                except Inspection_feedback.DoesNotExist:
                    data.update(
                        {
                            'created_by': user.username,
                            'updated_by': user.username,
                            'user': user.id,
                            'station': station.id,
                            }
                    )

                    serializer = InspectionFeedbackSerializer(data=data)
                    response_data = {'message': 'Inspection Feedback is created'}

                except Inspection_feedback.MultipleObjectsReturned:
                    return Response({"message": "Multiple feedbacks found for the particular date"}, status=status.HTTP_400_BAD_REQUEST)

                if serializer.is_valid(raise_exception=True):
                    serializer.save()
                    if 'status' in data:
                        serializer.validated_data['status'] = data['status']
                        serializer.save()
                        
                    if 'images' in request.FILES:
                        result = upload_inspection_feedback_images(request, serializer.instance)

                        if isinstance(result, Response):
                            return result
                    
                    serializer.save()
                    response_data.update(serializer.data)
                    
                    return Response(
                        response_data, 
                        status=status.HTTP_201_CREATED 
                        if 'created' in response_data['message'] else status.HTTP_200_OK
                        )
                else:
                    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
            else:
                return Response({'message': 'Permission Denied'}, status=status.HTTP_403_FORBIDDEN)

        except KeyError as e:
            return Response({"message": f"Data missing: {e.args[0]}"}, status=status.HTTP_400_BAD_REQUEST)

        except ValidationError as e:
            return Response({"message": repr(e)}, status=status.HTTP_400_BAD_REQUEST)
        
        except PermissionDenied as e:
            return Response({"message": str(e)}, status=status.HTTP_403_FORBIDDEN)

        except Exception as e:
            message = 'An error occurred while creating an Inspection Feedback'
            logging.exception(f"{message} in InspectionFeedbackApi: {repr(e)}")
            return Response({"message": message}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        
        
@permission_classes([IsAuthenticated, IsRailwayAdmin])
class UpdateFeedbackStatusApi(APIView):
    def put(self, request, pk):
        try:
            feedback = Inspection_feedback.objects.get(pk=pk)
            if feedback.status == 'Completed':
                feedback.status = 'Pending'
                feedback.save()
                return Response({'message': 'Feedback status updated to Pending'}, status=status.HTTP_200_OK)
            else:
                raise PermissionDenied("You don't have permission to update the status.") 

        except Inspection_feedback.DoesNotExist:
            return Response({"message": "Feedback not found"}, status=status.HTTP_404_NOT_FOUND)

        except PermissionDenied as e:
            return Response({"message": str(e)}, status=status.HTTP_403_FORBIDDEN)

        except Exception as e:
            message = 'An error occurred while updating feedback status'
            logging.exception(f"{message} in UpdateFeedbackStatusApi: {repr(e)}")
            return Response({"message": message}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


class ListRetrieveUpdateDeleteFeedbackApi(RetrieveUpdateDestroyAPIView):
    queryset = Inspection_feedback.objects.all()
    serializer_class = InspectionFeedbackSerializer
    permission_classes = [IsAuthenticated]


    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Inspection_feedback, pk=pk)

    def perform_update(self, serializer):
        try:
            user = self.request.user
            station = user.station
            role = user.user_type
            sup = role.name

            feedback_instance = serializer.instance

            # Check if the user is the owner of the feedback and has the necessary role to update
            if (
                feedback_instance.user == user
                and feedback_instance.status == 'Pending'
                and sup in ["supervisor", "contractor", "railway admin", "officer", "chi_sm"]
            ):
                if 'status' in self.request.data:
                    serializer.validated_data['status'] = self.request.data['status']
                
                serializer.save(updated_by=user.username)

                # Check if additional images are present in the request
                if 'images' in self.request.FILES:
                    result = upload_inspection_feedback_images(self.request, feedback_instance)
                    if isinstance(result, Response):
                        raise result  # Re-raise the response if there's an error during image upload

            else:
                raise PermissionDenied("You don't have permission to update this feedback.")

        except PermissionDenied as e:
            logging.exception(f"PermissionDenied in perform_update: {repr(e)}")
            raise e
        except Exception as e:
            logging.exception(f"An error occurred in perform_update: {repr(e)}")
            raise e

    def perform_destroy(self, instance):
        try:
            user = self.request.user
            feedback = self.get_object()

            if feedback.user == user:
                instance.delete()
            else:
                raise PermissionDenied("You don't have permission to delete this feedback.")

        except PermissionDenied as e:
            logging.exception(f"PermissionDenied in perform_destroy: {repr(e)}")
            raise e
        except Exception as e:
            logging.exception(f"An error occurred in perform_destroy: {repr(e)}")
            raise e
        
        
class ListFeedbacksByDateApi(ListAPIView):
    serializer_class = InspectionFeedbackSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        try:
            user = self.request.user
            station = user.station
            date_param = self.request.query_params.get('date', None)
            if not date_param:
                return []
            return Inspection_feedback.objects.filter(station=station, date=date_param)
            

Backend/templates/front/pdf/bde_daily.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Daily Summary BDE</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<style>
    .page {
        page-break-after: always;
        page-break-inside: avoid;
    }
</style>
<body>
    <div class="page">
        {% include "front/pdf/bde_daily_buyers_rating.html" %}
    </div>

    <!-- PASSENGER FEEDBACK FORM FOR STATION CLEANING -->
    {% if daily_report_for_bde %}
        <div class="page">
            {% if passenger_feedback_data %}
                {% for feedback in passenger_feedback_data %}
                    {% with forloop.counter as page_count %}
                        {% include 'front/pdf/pdf_p11.html' %}                       
                    {% endwith %}
                {% endfor %}
            {% elif inspection_feedback_data %}
                {% include 'front/pdf/inspection_feedback.html' %}
            {% else %}
                {% include 'front/pdf/pdf_p11.html' %}    
            {% endif %}
        </div>
    {% endif %}

    <!-- DAILY SHEET OF INSPECTION/USER FEEDBACK REGISTER -->
    <div class="page">
        {% include "front/pdf/pdf_p13.html" %}
    </div>

    <!-- DAILY EVALUATION SHEET FOR DEDUCTION PURPOSE -->
    <div class="page">
        {% include "front/pdf/pdf_p12.html" %}
    </div>

</body>

</html>

Backend/templates/front/pdf/bde_daily_buyers_rating.html
{% block body %}
    <head>
        <style>
            .container{
                display: flex; 
                flex-direction: column; 
                justify-content: start; 
                align-items: start;
            }
            .container .table{
                width: 100%;
            }
            .td{
                padding-top: 1px; 
                padding-left: 1;
            }
            .table table-bordered{
                font-size: 0.7rem;
                border-spacing: 0;
                border-collapse: collapse;
            }
            .table-sections{
                text-align: left;
                padding-left: 12px;
                padding-top: 1px;
                font-size: 9px;
            }
            .rating-td {
                padding-top: 4px; 
                font-size: larger;  
                text-align: right; 
                text-decoration: underline; 
                font-weight: bold;
            }
            .pax-td {
                text-align: left; 
                padding-left: 20px;
            }
            .pax-td1 {
                text-align: center; 
            }
            .taskk-td {
                border-left: 0.5px solid black; 
                height: 22.3px
            }
            .center-td {
                padding-top: 3px; 
                font-size: 9px;
            }
            .image-container {
                display: flex;
                flex-wrap: wrap;
                justify-content: space-evenly; 
                align-items: flex-start;
                padding: 20px; 
            }
            .image-set {
                margin: 10px; 
                flex: 0 0 auto;  
            }
            .image {
                width: 100px;
                height: 100px;
                object-fit: cover;
            }
        </style>
    </head>

    <div class="container">
        <h4>
            <u><center>DAILY BUYER'S EVALUATION SHEET</center></u>
        </h4>
        <table class="table">
            <tr style="width: 100%">
                <td style="width: 15%">
                    <b>Name of work:</b>
                </td>
                <td colspan="2" class="td">
                    <b>{{ station.name_of_work }}</b>
                </td>
            </tr>
            <tr>
                <td>
                    <b>Cleaning Contract by:</b>
                </td>
                <td colspan="2" class="td">
                    <b> {{ station.contract_by }}</b>
                </td>
            </tr>
            <tr>
                <td>
                    <b>Contract No.:</b>
                </td>
                <td colspan="2" class="td">
                    <b>{{ station.contract_no }}</b>
                </td>
            </tr>
            <tr colspan="3">
                <td style="padding-top: 4px;">
                    <b>DATE: {{ formatted_date }}</b>
                </td>
                <td class="rating-td">Daily Buyer's rating</td>
                <td style="text-align: right;">
                    <b>Downloaded Date: {{ date }}</b>
                </td>
            </tr>
        </table>
    </div>
    <div class="table-responsive container-fluid">
        <table        
            id="table"
            class="table table-bordered"
            style="font-size: 0.7rem; 
            border-spacing: 0;
            border-collapse: collapse"
            cellspacing="0"
            width="100%"
            align="center"
            border=".5"
            cellpadding="0">
            <thead class="bg-dark text-white">
                <tr>
                    <th rowspan="2" style="width: 2%">S No.</th>
                    <th rowspan="2" style="width: 35%">Description</th>
                    <th rowspan="2">Type Of Services</th>
                    <th rowspan="2" style="width: 5%; padding-top:1px;">
                        Cleaning Cycles
                        <br />
                        (days)
                        <br />
                        in 02
                        <br />
                        years
                    </th>
                    <th rowspan="2" style="width: 6%;">Type of cycle</th>
                    <th rowspan="2" style="width: 6%">
                        Cleaning Frequency
                        <br />
                        per
                        <br />
                        cycle (day)
                    </th>
                    <th rowspan="1">I</th>
                    <th rowspan="1">II</th>
                    <th rowspan="1">Remarks</th>
                </tr>
                <tr>
                    <th rowspan="1" style="width: 5%">
                        Max.
                        <br />
                        Buyer's
                        <br />
                        Rating
                    </th>
                    <th rowspan="1" style="width: 5%">
                        Buyer's
                        <br />
                        Rating (out of 4)
                        <br>
                        {% if timing %}
                            <hr>
                            {{ timing }}
                        {% endif %}
                    </th>
                </tr>   
            </thead>
            <tbody>
                <tr>
                    <td class="" style="text-align: left;">
                        <center>
                            <h6>A</h6>
                        </center>
                    </td>
                    <td class="table-sections" colspan="8">
                        <b>
                            <h6>Cleaning, Sanitation & Disinfection of 95 nos. of B, D & E Category stations (For {{ station.station_name }} station)</h6>
                        </b>
                    </td>
                </tr>
                {% for task, max_rating, ratings, ratings_num in tasks %}
                    <tr>
                        <td><center>{{ forloop.counter }}</center></td>
                        <td><center>{{ task.task_description }}</center></td>
                        <td><center><div style="padding-top:4px">{{ task.service_type }}</div></center></td>
                        <td><center>{{ task.cleaning_cycle_days }}</center></td>
                        <td><center>
                            <div style="padding-top:2px">
                            {% if task.get_cleaning_cycle_type_display == "Alternately" %}
                                Once in 2 days
                            {% else %}
                                {{ task.get_cleaning_cycle_type_display }}
                            {% endif %}
                        </center></div></td>
                        <td><center>{{ task.cleaning_cycle_day_freq }}</center></td>
                        <td><center>{{ max_rating }}</center></td>
                        <td>
                            <center>
                                <table style="width:100%">
                                    {% for rating in ratings %}
                                        <td style="width: {{ ratings_num }}%;height:30px;{% if not forloop.last %}border-right: 1px solid black;{% endif %};">
                                            {{ rating }}
                                        </td>
                                    {% endfor %}
                                </table>
                            </center>
                        </td>
                    </tr>
                {% endfor %}
                {% if colony %}
                    <tr>
                        <td class="center-td" style="text-align: left;">
                            <center>
                                <h6>B</h6>
                            </center>
                        </td>
                        <td class="table-sections" colspan="8">
                            <b>
                                <h6>Cleaning, Sanitation and Disinfection services of 3 nos. of 3 nos. of colonies i.e. Lakhisaral, Jahanabad, Guljiarbagh Colony  (For___________Colony)</h6>
                            </b>
                        </td>
                    </tr>
                
                    {% for task, max_rating, ratings in tasks %}
                        <tr>
                            <td><center>{{ forloop.counter }}</center></td>
                            <td><center>{{ task.task_description }}</center></td>
                            <td><center>{{ task.service_type }}</center></td>
                            <td><center>{{ task.cleaning_cycle_days }}</center></td>
                            <td><center>{{ task.get_cleaning_cycle_type_display }}</center></td>
                            <td><center>{{ task.cleaning_cycle_day_freq }}</center></td>
                            <td><center>{{ max_rating }}</center></td>
                            <td><center>
                            {% for rating in ratings %}
                                {{ rating }}
                            {% endfor %}
                        </center></td> 
                        </tr>
                    {% endfor %}
                {% endif %}
                <tr>
                    <td colspan="6" style="text-align: center;">Total </td>
                    <td><center>{{ total_max_ratings }}</center></td>
                    <td><center>{{ ratings_sum }}</center></td>
                </tr>
                <tr>
                    <td colspan="7" style="text-align: center;">Buyer’s daily average rating in percentage = Total in column IIx100/ Total in Column I </td>
                    <td><center>{{ avg_rating }}%</center></td>
                </tr>
            </tbody>
        </table>
    </div>
    
    <table style="width: 100%; margin-top:50px">
        <tr style="width: 100%">
            <td style="font-weight: 600; font-size: 9px; width: 500%;">
                <p>
                    <h3 style=" color: green;">
                        {% for verified_shift in verified_shifts %}
                            {% with verified_shift.verified_by as verified_by %}
                                {% if verified_by.user_type.name == "supervisor" or verified_by.user_type.name == "chi_sm" %}
                                    verified by {{ verified_by.username }}
                                {% endif %}
                            {% endwith %}
                        {% endfor %}
                    </h3>
                    Signature of CHI/SSE/JE
                </p>
                
            
            </td>
            <td style="font-weight: 600; font-size: 9px; width: 50%;">
                <p>
                    <h3 style="color: green;">
                        {% for verified_shift in verified_shifts %}
                            {% with verified_shift.verified_by as verified_by %}
                                {% if verified_by.user_type.name == "contractor" %}
                                    verified by {{ verified_by.username }}
                                {% endif %}
                            {% endwith %}
                        {% endfor %}
                    </h3>
                    Signature of Contractor/Authorized Signatory
                </p>
            
            </td>
        </tr>
    </table>

    <div class="container">
        {% if showimages %}
            <hr>
            {% for task_images in images %}
                <table class="table">
                    <tr style="width: 100%">
                        <td>
                            <h2>Task No: {{ forloop.counter }} {% if not task_images %} <span style="color: red;"> NIL </span>{% endif %}</h2> 
                        </td>
                        {% for occur_image_sets in task_images %}
                            <td style="font-weight: bold; padding-top: 20px;">
                                <u>Occurrence No: {{ forloop.counter }}</u> {% if not occur_image_sets %} <span style="color: red;">No Images</span>{% endif %}<br/><br/>
                                {% for image in occur_image_sets %}
                                    {% if is_prod %}
                                        <img class="image img-fluid mr-2" src="{{ image.image.url }}" alt="Image"><br/>
                                    {% else %}
                                        <img class="image img-fluid mr-2" src="{{ image.image.path }}" alt="Image"><br/><br/>
                                    {% endif %}
                                    <b> Uploaded By: </b> {{ image.user_name }} <br>
                                    <b> Uploaded At: </b> {{ image.created_at }} <br>
                                    <b> Uploaded From: </b> {{ image.latitude }}, {{ image.longitude }} <br/>
                                {% endfor %}
                            </td>
                        {% endfor %}
                    </tr>
                </table>
                <hr>
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}